TARGET_ID="harp-dfe-xczu67dr"
TARGET_MACHINE="harp-dfe-xczu67dr"
TARGET_ALIASES=""
TARGET_PLATFORM="xilinx-zynqmp"
TARGET_PRODUCT="xilinx-zynqmp-harp-dfe"
TARGET_BASELINE="scarthgap"
TARGET_SUPPORT_LEVEL="Parse-Validated"
TARGET_DEFAULT_IMAGE="petalinux-image-minimal"
