TARGET_ID="zynqmp-generic"
TARGET_MACHINE="zynqmp-generic"
TARGET_ALIASES=""
TARGET_PLATFORM="xilinx-zynqmp"
TARGET_PRODUCT=""
TARGET_BASELINE="scarthgap"
TARGET_SUPPORT_LEVEL="Parse-Validated"
TARGET_DEFAULT_IMAGE="petalinux-image-minimal"
