PLATFORM_BASELINE_ID="kirkstone"
PLATFORM_DISTRO="fsl-qoriq"
PLATFORM_LAYERS="
components/layers/bsp/nxp/meta-freescale
components/layers/bsp/nxp/meta-qoriq
components/layers/bsp/nxp/meta-freescale-distro
components/layers/baselines/kirkstone/meta-virtualization
"
PLATFORM_LOCAL_CONF="platforms/nxp/conf/local.conf.fragment"
