# Xilinx ZynqMP / Zynq platform
# PLATFORM_MACHINE_LAYER: BSP layer directory name; used by setup-env.sh to locate the vendor layer
PLATFORM_MACHINE_LAYER="meta-xilinx"

PLATFORM_BSP_LAYERS="meta-xilinx-tools meta-petalinux meta-tpm meta-microblaze \
meta-xilinx-bsp meta-xilinx-core meta-xilinx-contrib meta-xilinx-standalone \
meta-qt5 meta-virtualization meta-openamp meta-xilinx-tsn"

PLATFORM_DISTRO="petalinux"
