TARGET_ID="stm32mp15-disco"
TARGET_MACHINE="stm32mp15-disco"
TARGET_ALIASES="stm32mp15-common"
TARGET_PLATFORM="stm32mp"
TARGET_PRODUCT=""
TARGET_BASELINE="scarthgap"
TARGET_SUPPORT_LEVEL="Parse-Validated"
TARGET_DEFAULT_IMAGE="core-image-minimal"
