BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-tegra-user"
BBFILE_PATTERN_meta-tegra-user = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tegra-user = "6"

LAYERSERIES_COMPAT_meta-tegra-user = "scarthgap"
LICENSE_PATH += "${LAYERDIR}/licenses"
