# Common IMAGE_INSTALL additions for all platforms
COMMON_TOOLS_IMAGE = " \
    mtd-utils \
    i2c-tools \
    util-linux \
    procps \
    mmc-utils \
    iproute2 \
    "

CORE_IMAGE_EXTRA_INSTALL = " \
    watchdog-feeder \
    "

IMAGE_INSTALL:append = " \
    ${COMMON_TOOLS_IMAGE} \
    ${CORE_IMAGE_EXTRA_INSTALL} \
    "
