TARGET_ID="raspberrypi4-64"
TARGET_MACHINE="raspberrypi4-64"
TARGET_ALIASES=""
TARGET_PLATFORM="raspberrypi"
TARGET_PRODUCT=""
TARGET_BASELINE="whinlatter"
TARGET_SUPPORT_LEVEL="Parse-Validated"
TARGET_DEFAULT_IMAGE="core-image-minimal"
