TARGET_ID="raspberrypi0-2w"
TARGET_MACHINE="raspberrypi0-2w"
TARGET_ALIASES=""
TARGET_PLATFORM="raspberrypi"
TARGET_PRODUCT=""
TARGET_BASELINE="whinlatter"
TARGET_SUPPORT_LEVEL="Declared"
TARGET_DEFAULT_IMAGE="core-image-minimal"
