BASELINE_ID="whinlatter"
BASELINE_SERIES="whinlatter"
BASELINE_DESCRIPTION="Yocto Project Whinlatter series"
BASELINE_OEROOT="components/layers/baselines/whinlatter/poky"
BASELINE_LAYERS="
components/layers/baselines/whinlatter/poky/meta
components/layers/baselines/whinlatter/poky/meta-poky
components/layers/baselines/whinlatter/poky/meta-yocto-bsp
components/layers/baselines/whinlatter/meta-openembedded/meta-oe
components/layers/baselines/whinlatter/meta-openembedded/meta-multimedia
components/layers/baselines/whinlatter/meta-openembedded/meta-python
components/layers/baselines/whinlatter/meta-openembedded/meta-networking
components/layers/baselines/whinlatter/meta-openembedded/meta-gnome
components/layers/baselines/whinlatter/meta-openembedded/meta-filesystems
components/layers/baselines/whinlatter/meta-openembedded/meta-webserver
components/layers/baselines/whinlatter/meta-openembedded/meta-perl
components/layers/baselines/whinlatter/meta-openembedded/meta-xfce
components/layers/baselines/whinlatter/meta-openembedded/meta-initramfs
components/layers/baselines/whinlatter/meta-arm/meta-arm-toolchain
components/layers/baselines/whinlatter/meta-arm/meta-arm
components/layers/baselines/whinlatter/meta-arm/meta-arm-bsp
"
