TARGET_ID="jetson-agx-orin-devkit"
TARGET_MACHINE="jetson-agx-orin-devkit"
TARGET_ALIASES=""
TARGET_PLATFORM="tegra"
TARGET_PRODUCT=""
TARGET_BASELINE="whinlatter"
TARGET_SUPPORT_LEVEL="Declared"
TARGET_DEFAULT_IMAGE="core-image-minimal"
