BASELINE_ID="kirkstone"
BASELINE_SERIES="kirkstone"
BASELINE_DESCRIPTION="Yocto Project 4.0 LTS for the QorIQ SDK stack"
BASELINE_OEROOT="components/layers/baselines/kirkstone/poky"
BASELINE_LAYERS="
components/layers/baselines/kirkstone/poky/meta
components/layers/baselines/kirkstone/poky/meta-poky
components/layers/baselines/kirkstone/poky/meta-yocto-bsp
components/layers/baselines/kirkstone/meta-openembedded/meta-oe
components/layers/baselines/kirkstone/meta-openembedded/meta-multimedia
components/layers/baselines/kirkstone/meta-openembedded/meta-python
components/layers/baselines/kirkstone/meta-openembedded/meta-networking
components/layers/baselines/kirkstone/meta-openembedded/meta-gnome
components/layers/baselines/kirkstone/meta-openembedded/meta-filesystems
components/layers/baselines/kirkstone/meta-openembedded/meta-webserver
components/layers/baselines/kirkstone/meta-openembedded/meta-perl
components/layers/baselines/kirkstone/meta-openembedded/meta-xfce
components/layers/baselines/kirkstone/meta-openembedded/meta-initramfs
components/layers/baselines/kirkstone/meta-arm/meta-arm-toolchain
components/layers/baselines/kirkstone/meta-arm/meta-arm
components/layers/baselines/kirkstone/meta-arm/meta-arm-bsp
"
