# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-xilinx-user"
BBFILE_PATTERN_meta-xilinx-user = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-xilinx-user = "6"

LAYERSERIES_COMPAT_meta-xilinx-user = "scarthgap"
LICENSE_PATH += "${LAYERDIR}/licenses"
