PLATFORM_BASELINE_ID="scarthgap"
PLATFORM_DISTRO="petalinux"
PLATFORM_LAYERS="
components/layers/bsp/xilinx/meta-xilinx-tools
components/layers/bsp/xilinx/meta-petalinux
components/layers/bsp/xilinx/meta-security/meta-tpm
components/layers/bsp/xilinx/meta-xilinx/meta-microblaze
components/layers/bsp/xilinx/meta-xilinx/meta-xilinx-bsp
components/layers/bsp/xilinx/meta-xilinx/meta-xilinx-core
components/layers/bsp/xilinx/meta-xilinx/meta-xilinx-contrib
components/layers/bsp/xilinx/meta-xilinx/meta-xilinx-standalone
components/layers/tools/meta-qt5
components/layers/bsp/xilinx/meta-virtualization
components/layers/bsp/xilinx/meta-openamp
components/layers/bsp/xilinx/meta-xilinx-tsn
"
PLATFORM_LOCAL_CONF="platforms/xilinx-zynqmp/conf/local.conf.fragment"
