# XSA hardware definition file
HDF_BASE = "file://"
HDF_PATH = "/home2/yang.xu/tool/sources/yocto-forall/components/descriptions/system.xsa"

# OVERRIDES:prepend = "mytest:"
RM_WORK_EXCLUDE += " \
                    device-tree \
                    petalinux-image-minimal \
                    fsbl-firmware \
                    u-boot-xlnx \
                    u-boot-zynq-scr \
                    arm-trusted-firmware \
                   "