# OVERRIDES:prepend = "mytest:"
RM_WORK_EXCLUDE += " \
                    device-tree \
                    petalinux-image-minimal \
                    fsbl-firmware \
                    u-boot-xlnx \
                    u-boot-zynq-scr \
                    arm-trusted-firmware \
                   "

# Enable Xilinx ESW tools for XSA processing
# This enables device-tree generation from XSA using XSCT/HSI
XILINX_WITH_ESW = "xsct"


# XSA hardware definition file
# In project-spec/configs/config or local.conf
HDF_MACHINE = "zynqmp-generic"
HDF_BASE = "file://"
HDF_PATH = "${TOPDIR}/../components/descriptions/system.xsa"

PREFERRED_PROVIDER_virtual/dtb = "device-tree"
EXTRA_IMAGEDEPENDS += "device-tree"
# INHERIT:remove = "uninative"