BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-stm32mp-user"
BBFILE_PATTERN_meta-stm32mp-user = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-stm32mp-user = "6"

LAYERSERIES_COMPAT_meta-stm32mp-user = "scarthgap"
LICENSE_PATH += "${LAYERDIR}/licenses"
