# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "xilinx-zynqmp-harp-dfe"
BBFILE_PATTERN_xilinx-zynqmp-harp-dfe = "^${LAYERDIR}/"
BBFILE_PRIORITY_xilinx-zynqmp-harp-dfe = "7"

LAYERDEPENDS_xilinx-zynqmp-harp-dfe = "core xilinx xilinx-bsp"
LAYERSERIES_COMPAT_xilinx-zynqmp-harp-dfe = "scarthgap"
LICENSE_PATH += "${LAYERDIR}/licenses"
