BASELINE_ID="scarthgap"
BASELINE_SERIES="scarthgap"
BASELINE_DESCRIPTION="Yocto Project 5.0 LTS"
BASELINE_OEROOT="components/layers/baselines/scarthgap/poky"
BASELINE_LAYERS="
components/layers/baselines/scarthgap/poky/meta
components/layers/baselines/scarthgap/poky/meta-poky
components/layers/baselines/scarthgap/poky/meta-yocto-bsp
components/layers/baselines/scarthgap/meta-openembedded/meta-oe
components/layers/baselines/scarthgap/meta-openembedded/meta-multimedia
components/layers/baselines/scarthgap/meta-openembedded/meta-python
components/layers/baselines/scarthgap/meta-openembedded/meta-networking
components/layers/baselines/scarthgap/meta-openembedded/meta-gnome
components/layers/baselines/scarthgap/meta-openembedded/meta-filesystems
components/layers/baselines/scarthgap/meta-openembedded/meta-webserver
components/layers/baselines/scarthgap/meta-openembedded/meta-perl
components/layers/baselines/scarthgap/meta-openembedded/meta-xfce
components/layers/baselines/scarthgap/meta-openembedded/meta-initramfs
components/layers/baselines/scarthgap/meta-arm/meta-arm-toolchain
components/layers/baselines/scarthgap/meta-arm/meta-arm
components/layers/baselines/scarthgap/meta-arm/meta-arm-bsp
"
